#!/usr/bin/env bash

cd ..

mkdir -p Assembly

echo "#pragma once" > Source/Configuration.h
echo "#define LINUX" >> Source/Configuration.h
#echo "#define DEBUG" >> Source/Configuration.h

read -p "Source File: " source
file="$source"_$(basename $0).asm

clear

clang++ -S -g -Wall -std=c++17 Source/$source.cpp -o Assembly/$file