#!/usr/bin/env bash

cd ..

mkdir -p Binaries

echo "#pragma once" > Source/Configuration.h
echo "#define LINUX" >> Source/Configuration.h

read -p "Source File: " source
file="$source"_$(basename $0)

clear

clang++ -O3 -std=c++17 Source/$source.cpp -o Binaries/$file

./Binaries/$file